version: 0.2

phases:
    pre_build:
        commands:
            - echo Restore started on `date`
            - dotnet build CocShopProject/CocShop.WebAPi.csproj --configuration Release
    build:
        commands:
            - echo Build started on `date`
            - dotnet publish CocShopProject/CocShop.WebAPi.csproj -o ./build_output --configuration Release
artifacts:
    files:
        - '**/*'
    base-directory: 'build_output'